#!/bin/bash
# SessionStart Hook - Context Review
# Automatically loads and reports context changes at session initialization
#
# TEMPLATE: Deploy by copying to .claude/hooks/ in any project.
# Uses relative paths -- must be run from project root.

set -e

# Pull latest changes if in a git repo with a remote
if git rev-parse --git-dir >/dev/null 2>&1; then
  git pull --ff-only origin main 2>/dev/null || true
fi

CONTEXT_DIR=".claude/context"
STATE_FILE=".claude/hooks/.last-session-state"
OUTPUT_FILE=".claude/LAST_SESSION.md"

CURRENT_TIME=$(date +%s)

# Initialize output
cat > "$OUTPUT_FILE" << 'EOF'
# Last Session Status

**Auto-generated by SessionStart hook**
**Updated:**
EOF

echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Check for handoff doc
if [ -f ".claude/NEXT_SESSION_PLAN.md" ]; then
  echo "## Handoff Available" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "Read \`.claude/NEXT_SESSION_PLAN.md\` for session priorities and state." >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

# Check context directory
if [ ! -d "$CONTEXT_DIR" ]; then
  echo "No context directory found at $CONTEXT_DIR" >> "$OUTPUT_FILE"
  exit 0
fi

# Initialize or read last session state
if [ -f "$STATE_FILE" ]; then
  LAST_SESSION_TIME=$(cat "$STATE_FILE")
else
  LAST_SESSION_TIME=0
  echo "## First Session with Context System" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
fi

echo "$CURRENT_TIME" > "$STATE_FILE"

# Check for context file changes
CHANGES_FOUND=false
CHANGE_SUMMARY=""

for context_file in "$CONTEXT_DIR"/*.md; do
  if [ -f "$context_file" ]; then
    filename=$(basename "$context_file" .md)

    if [[ "$OSTYPE" == "darwin"* ]]; then
      mod_time=$(stat -f %m "$context_file")
    else
      mod_time=$(stat -c %Y "$context_file")
    fi

    if [ $mod_time -gt $LAST_SESSION_TIME ]; then
      CHANGES_FOUND=true
      if [[ "$OSTYPE" == "darwin"* ]]; then
        mod_date=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "$context_file")
      else
        mod_date=$(date -d "@$mod_time" "+%Y-%m-%d %H:%M")
      fi
      CHANGE_SUMMARY="${CHANGE_SUMMARY}- **${filename}**: Updated ${mod_date}\n"
    fi
  fi
done

if [ "$CHANGES_FOUND" = true ]; then
  echo "## Context Updates Since Last Session" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo -e "$CHANGE_SUMMARY" >> "$OUTPUT_FILE"
else
  echo "## No Context Changes Since Last Session" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"

# List all available contexts
echo "## Available Contexts" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for context_file in "$CONTEXT_DIR"/*.md; do
  if [ -f "$context_file" ] && [[ ! "$context_file" =~ README ]]; then
    filename=$(basename "$context_file" .md)
    size=$(wc -l < "$context_file" | tr -d ' ')
    echo "- **${filename}** (${size} lines)" >> "$OUTPUT_FILE"
  fi
done

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "**Read NEXT_SESSION_PLAN.md first. Update context files immediately when you learn something.**" >> "$OUTPUT_FILE"

exit 0
